/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author Diego
 */
public class ViewNew extends javax.swing.JPanel {

    /**
     * Creates new form ViewNew
     */
    public ViewNew() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jp_reg = new javax.swing.JPanel();
        jp_password = new javax.swing.JPasswordField();
        jbtn_registrar = new javax.swing.JButton();
        jcmb_nivel = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtf_user = new javax.swing.JTextField();
        jtf_name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setLayout(null);

        jp_reg.setLayout(null);
        jp_reg.add(jp_password);
        jp_password.setBounds(350, 230, 190, 20);

        jbtn_registrar.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        jbtn_registrar.setText("Registrarse");
        jp_reg.add(jbtn_registrar);
        jbtn_registrar.setBounds(380, 310, 110, 29);

        jcmb_nivel.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        jcmb_nivel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vendedor", "Administrador", "SuperUsuario" }));
        jp_reg.add(jcmb_nivel);
        jcmb_nivel.setBounds(370, 270, 110, 26);

        jLabel4.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        jLabel4.setText("Contraseña:");
        jp_reg.add(jLabel4);
        jLabel4.setBounds(300, 200, 67, 20);

        jLabel5.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        jLabel5.setText("Nivel:");
        jp_reg.add(jLabel5);
        jLabel5.setBounds(310, 270, 60, 20);
        jp_reg.add(jtf_user);
        jtf_user.setBounds(350, 170, 190, 20);

        jtf_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_nameActionPerformed(evt);
            }
        });
        jp_reg.add(jtf_name);
        jtf_name.setBounds(350, 130, 190, 20);

        jLabel3.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        jLabel3.setText("Usuario:");
        jp_reg.add(jLabel3);
        jLabel3.setBounds(300, 150, 70, 20);

        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        jLabel2.setText("Nombre:");
        jp_reg.add(jLabel2);
        jLabel2.setBounds(300, 100, 60, 20);

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 36)); // NOI18N
        jLabel1.setText("Registrate.");
        jp_reg.add(jLabel1);
        jLabel1.setBounds(350, 50, 140, 39);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondo1.jpg"))); // NOI18N
        jp_reg.add(jLabel6);
        jLabel6.setBounds(0, 0, 580, 450);

        add(jp_reg);
        jp_reg.setBounds(0, 0, 580, 450);
    }// </editor-fold>//GEN-END:initComponents

    private void jtf_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_nameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    public javax.swing.JButton jbtn_registrar;
    public javax.swing.JComboBox<String> jcmb_nivel;
    public javax.swing.JPasswordField jp_password;
    public javax.swing.JPanel jp_reg;
    public javax.swing.JTextField jtf_name;
    public javax.swing.JTextField jtf_user;
    // End of variables declaration//GEN-END:variables
}
